version: '3'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3666:3000"
    environment:
      - NODE_ENV=production
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3666"]
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  default:
    name: brian-rabil-network
    driver: bridge
